apiVersion: v1
kind: Service
metadata:
  labels:
    app: findme
    version: v1
  name: findme
  namespace: default
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: findme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: findme
    version: v1
  name: findme
  namespace: default
spec:
  selector:
    matchLabels:
      app: findme
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: findme
        version: v1
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      serviceAccountName: findme
      containers:
        - image: docker.io/cmwylie19/find-me:latest
          name: findme
          env:
            - name: REACT_APP_ENV
              value: prod
          ports:
            - containerPort: 80
              name: http
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: findme
