# permissions for end users to view findmes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: findme-viewer-role
rules:
- apiGroups:
  - application.caseywylie.io
  resources:
  - findmes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.caseywylie.io
  resources:
  - findmes/status
  verbs:
  - get
