apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-metrics
    version: v1
  name: go-metrics
  namespace: default
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: go-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-metrics
    version: v1
  name: go-metrics
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-metrics
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: go-metrics
        version: v1
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      serviceAccountName: go-metrics
      containers:
        - image: docker.io/cmwylie19/go-metrics:latest
          name: go-metrics
          env:
            - name: REACT_APP_ENV
              value: prod
          ports:
            - containerPort: 8080
              name: http
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-metrics
