apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
spec:
  hosts:
  - "*"
  gateways:
  - default
  http:
  - match:
    - uri:
        exact: /get
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.findme.name }}
        port:
          number: 80